kind: pipeline
type: docker
name: default

steps:

  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: drone-cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./node_modules
        # We can only mount volume caches into the working directory, so all steps which use Gradle must have
        # the GRADLE_USER_HOME environment variable pointing here.
        - ./gradle_cache
        - ./sonar_cache

  - name: fetch-fds-submodule
    image: alpine/git:v2.26.2
    commands:
      - echo "$${BITBUCKET_SSH_KEY}" > bitbucket_ssh_key
      - chmod 600 bitbucket_ssh_key
      - export GIT_SSH_COMMAND="ssh -i bitbucket_ssh_key -F /dev/null  -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
      - git submodule update --init --recursive
    environment:
      BITBUCKET_SSH_KEY:
        from_secret: bitbucket_ssh_key

  - name: build-frontend
    image: node:10
    commands:
      - cd fivium-design-system-core && npm install && npx gulp build && cd ..
      - npm install
      - npx gulp buildAll

  - name: build-backend
    image: eclipse-temurin:17-jdk
    environment:
      SONAR_TOKEN:
        from_secret: sonarcloud_token
    commands:
      - chmod +x gradlew
      - ./gradlew checkstyleMain test bootJar sonarqube

  - name: sync-reports
    image: alpine:3.16.0
    commands:
      - mkdir -p /var/webfiles/${DRONE_BUILD_NUMBER}
      - cp -r build/reports /var/webfiles/${DRONE_BUILD_NUMBER}
    volumes:
      - name: webfiles
        path: /var/webfiles
    when:
      status: [ success, failure ]

  - name: publish-docker-develop
    image: plugins/docker:19.03.8
    settings:
      registry: quay.io
      repo: quay.io/fivium/supply-chain-action-plan
      tags:
        - develop
      config:
        from_secret: docker_config
    when:
      branch:
        - develop
      status:
        - success

  - name: publish-docker
    image: plugins/docker:19.03.8
    settings:
      registry: quay.io
      repo: quay.io/fivium/supply-chain-action-plan
      tags:
        - ${DRONE_BRANCH/\//-}-${DRONE_BUILD_NUMBER}
      config:
        from_secret: docker_config
    when:
      branch:
        - main
        - hotfix/**
        - release/**
      status:
        - success

  - name: trivy-build-image
    image: docker:20.10.9
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
    commands:
      - docker build -t quay.io/fivium/scap:trivy-scan-target .

  - name: trivy-scan
    image: aquasec/trivy:0.20.0
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
      - name: drone-trivy-cache
        path: /root/trivy-cache
      - name: webfiles
        path: /var/webfiles
    commands:
      # timeout set as initial cache population can seemingly take a while sometimes
      - trivy --format template --template "@contrib/html.tpl" -o /var/webfiles/${DRONE_BUILD_NUMBER}/trivy-scan.html image --timeout 30m --exit-code 1 quay.io/fivium/scap:trivy-scan-target
    when:
      status:
        - success

  - name: deploy-dev-st
    image: plugins/downstream:linux-amd64
    settings:
      server: https://drone.fivium.co.uk
      token:
        from_secret: drone_token
      fork: true
      repositories:
        - fiviumuk/fivium-dev-app@master
    when:
      branch:
        - develop
      status:
        - success

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: drone-cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./node_modules
        - ./gradle_cache
        - ./sonar_cache

  - name: slack
    image: plugins/slack
    settings:
      webhook: https://hooks.slack.com/services/UPDATE_WEBHOOK
      channel: oga-scap-builds
      template: "*{{build.status}}* <{{build.link}}|Commit {{truncate build.commit 7}} on {{build.branch}} by ${DRONE_COMMIT_AUTHOR_NAME}>\nReports published to: http://drone-assets.fivium.local:9090/scap/{{build.number}}/"
    when:
      status: [ success, failure ]

trigger:
  event:
    include:
    - push

volumes:
  - name: webfiles
    host:
      path: /home/fivium/www/supply-chain-action-plan

  - name: drone-cache
    host:
      path: /home/fivium/drone-cache

  - name: docker-sock
    host:
      path: /var/run/docker.sock

  - name: drone-trivy-cache
    host:
      path: /root/.cache/

---

kind: secret
name: docker_config
data: BUILD_SECRET
---

kind: secret
name: sonarcloud_token
data: BUILD_SECRET

---

kind: secret
name: bitbucket_ssh_key
data: GvFYzL2NOWOfDTAVnaxB0KKfOBr98VBicFIjRUe5I8IMA+2Ast2O6irTNY7Y6GRGgpZ4fxqHo42DvOLycgPOw7/hC/HZrAyUNyfF7RFQELnLPx0aXme3iIfkeyVXKenarGPSwU0Q6i4yiVbkJtF0zNRI+A72OWoiOy4SXV1WhnY1cWthGjKlpgnpSZuHrww/80Kr7R+2CNkPRq1jUYqDUC2PuHf9SadtJrAAMqRSQZzwe/5GaT+/RAaRlX/z2eKJe++GBRRowvbF9/rqhoeiab5+uMd9Uba9TFwSWIfIAAZfZdgEA6PgcdDGYNHfaHMFKMEZbuk9u0fiOz4WAJiuRV4KJFNVdv/ykQl5EN2GOA4bfTvZrZs7KoxN5gnrXsfhANk4JC4+ZJbAIctzl1sN2kdZqbRx/BKkDsZKgdWmYd874cgruQUNgxV3IEKw9086w2455fYTfPQMJOAplI4nJOaZ+pmv7diIw84CN8H9dXDAsZmYet8Po1EBkOQWrAlmueMXh6YvqJb7/rOTMT0t9e+io4b5phA1wNf4aELFlZeYkhohA/LLUaz/6Hu3OJN6li/wtrLEbZOp26Qgqe6W99tntdriAYEOJAtnfLZlYQ8OybYzuZvjUdRmHcVgG87xJjwkg1AZEwKqep+JikgdXBGSjZKxph2ykAHfiavpU7kPg7BywgsvFo8mvxZ7wTYZGHG9f1p0l9PvMXRFDZzWXCFOWm9hwRDSc/uIvErpBTEJDlN7X939MxewoTAFaiSDVIKNZu1mM1wgyEIt+vELGt2OBNzrPrrxYdv6kdqBHcAfnnp52Uj5ZDDJWCrteAcNJPRLkdigCRb5u+U8kaiujJcJGnCp3hqDiCoctYdf+Oom39q/wur5wzLjx8TmFGwCUNeYkqrctKS+UX6YXYA+TvfUFXXxqzsf6vlQ5Wuqv0oynQ07tZZiSXcGkXGqCH3QnyhJbWWzvCfC1/xVrvLkGfz6qs4D5WAYhUEFbseiqJ9o7IUzP6IuAKf/E3ow2kxEoA+G7ShKbvmgfaQbWgeWqXOTV5l5lOa9JPSs5S82YK7oRDvHxuZgxiV1yJthyG2OK1vkeStKqtGE/RyllHVQFaqRoMG9pJQEwvRSL93/+eTpY+nuXsR51YpGYZv2CcEWyD2rF8GeEYc3llNClTBP10MF8j1kJJlOtag3U1eaJKhp/rtX2jZd69HS1cWKTwfxWqYiECA36Id+fD/Pt+tBUwkG0HL9CAjh2lI171zCZ/pFambaFdJ/Wd5kfWekgX9/UsEdLtMiFywUbrN7YAUkSUuvJILHQYyabFBdEEwPE6Ai/oDUKyD/7KYm0rrzam5D48cYikf5Jh7dUf7m6kju7a9TRAGC3lxDSfxpuLpsfa6OdRKFhpLwVJHO6UUCOANAyUS9abLRbL5fFZ+a8rOkMUoPxSISMEHC2mw8CuqsSS1pQ74quJdvVDN9LgLjFFMwH1EUIHvYSg6PoX0TK2SKz4E3CPwpKHyMgUSGitremWAch5Z57hXt9CaomT1vDUumM5sqJbJ7nhcWwzLJHC1Lrz1okAg4BYZ7FtHU65vn4dAChBgpre1KhGr0FWL9nOoAvX9TCDepz+MJSluza4M6ekIaNxnRl9Ib0QiigqxUB1FirlKXTMz8s5RI9uQ5eZaX7AbCBfr65JHe8Xc4a0i7LRmg7tiKN98hyR2pcFZmPcNqhv5CcFNkuL2nEZdpZjaWpWbLx00C/hLr2b+unatMpDxzbkbkPfg86YZVb2byfOuFUqNSDBWLxCQRBe/IVzP8LJb6EcIWjVR0sFBxyntqI3otiO1340K0vAupYIUaPgu9Ln8MlQEupKow8jguLIxxs4jAJU4pHMBednaKoNeNUdJI7e48sh+ONMrUKEaIbW6WWfj08wmILf8gcEbGjyy6l1N3pPlezgl6m1H7U/r9mjOEdxvtN/PMppV/jWVp02pPirJ5ypASM8BARQlNJ3yePw+o7mLiYkOBBRrPgRvh2XxlP14Q8/na21jwKuAW06JfrAjbyH4yN3bkXzfrwYvdsk7bjB8xCjynV3CwFnWPYLRJqnHnHXyit7bN6sqRzfwb+lHnoaDuLCiat/jFWuSXqhyJuG8ibrP9fkP0GNnwzkbmDc0QcAogIxfZJj/sEzTY6veJyOjB/JqzIreNYBQlSpsMDAni+SJ5y2OMZ1AuNzRWqa1r284mofkfrjwY69ET0qtKVnQYGKyy+Fv/uKmCnp3kryfR/ANEATU0Eq5zcFid8oJA/xX7m/GWKD2iF6mN9Mu9flPlKMDnXqofHf8r3X9ehE0Q8Z36bObGRlJGh31zVSSsD/ZrDJRssmOUcTp2xHFewIHZkO2P87GWhXsdgQN4OvTMLD82pbXnoDo5Nv8wuLsCA7/Mc8iKrdBeBESxskcWT1W8poVqcSPVumbFR0pZQhrje0efo+u+N6UmEIL/HDBSXLpBjOh4gq8068KTxvzuStKOogIRNtTqFjF6HvOB+m+pAAkuOt+OkkAmzBzEZ+RVmirnixppvASX+Qm+G0bMRLR1CLyR6TCMFcdfpUJzZVy65jt/Goq8h0Ifqil7BJze0wLYwRwS89kFK0SrHP//n29cxqHOKK0UX3ET8+fBWe8irT8dn+whmPwzFppPoNfbr/PWuQq6b73GxppjBgZX6cdMmtSyIfUWgkm/DUfUHd8i7PfFeHwXcizUHvlSYyQOlbkiMqSehnpuu3pD05efEcJf+EXMU0TQFhtyc8aIBrdGwbR2UlDidRZbO4vaxNz99rL6sWkmlWbECU3ol70bsG8LtyjU19kqKHlA9NJ8YwOAL8arcblUGqFesSNJtwwHKdWda72afq2mrTSVg8dx0ETIKUuMGRkc7sSqiiRh21sdlldRpZR8WS0ptzqxiE2cdSYrN7O7UXsLeL2Vt4qqRtXK7rJsvo9A9Y9HU9ZuYJ9h/LeBkr3eG3YzcvfHftOrrizZp5U0uxmVdpK+rUBVzJ+dpPMPOPutkZVCrt3FRT3VnrU7wDxAEq06lAp37f/GHWAVW1Jnfvv7kVbEcknuB++iOkKf5G2UdGTAs1drgLJ7+HzInv5Pw6qPqPEOoas1Voy98j8mdFRhJmY0bhv480y90Nd6PC0yriMZpWZUFNwLZZ6DKyzZDkdE/OgguhlVfFEktgUfFOfqSENG7DYIxLbuwqEkDdH3aDjTKuzs4PASf8F6cDw1Qzlk0Tb0oDFJEJBoF7k4yyWQvVSrDf9+D9lMa6no5z0cKvxuXNcD9YvYV5+LoYerA471muIwbEqwyNYiHb+k1AxUyC2imreE6/KWTMkYV6rO61dG1pnNdwi/6I/itgAAHRf8lI+wAfsWiimLexIRrs8mbBN/39uSJx8Im2OkpbBBc8f4K38l/TdqO5gYD92/CHVuhWTRyUuiNg/9rJVTZmei9brWRWZLJn3NwQj23B5IhGD/5h8RyEd4s3/v25fUznOb3lDpvjoK/sZwds3xtlJM6+g2f92oT3P68qKa5q+jbWIyH2/VL7nJR+lY9Au9XJXP+Iiy13+hMCh/wNQ=

---

kind: secret
name: drone_token
data: BUILD_SECRET