kind: pipeline
type: docker
name: default

steps:

  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: drone-cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./node_modules
        # We can only mount volume caches into the working directory, so all steps which use Gradle must have
        # the GRADLE_USER_HOME environment variable pointing here.
        - ./gradle_cache
        - ./sonar_cache

  - name: fetch-fds-submodule
    image: alpine/git:v2.26.2
    commands:
      - echo "$${BITBUCKET_SSH_KEY}" > bitbucket_ssh_key
      - chmod 600 bitbucket_ssh_key
      - export GIT_SSH_COMMAND="ssh -i bitbucket_ssh_key -F /dev/null  -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
      - git submodule update --init --recursive
    environment:
      BITBUCKET_SSH_KEY:
        from_secret: bitbucket_ssh_key

  - name: build-frontend
    image: node:10
    commands:
      - cd fivium-design-system-core && npm install && npx gulp build && cd ..
      - npm install
      - npx gulp buildAll

  - name: build-backend
    image: eclipse-temurin:17-jdk
    environment:
      SONAR_TOKEN:
        from_secret: sonarcloud_token
    commands:
      - chmod +x gradlew
      - ./gradlew checkstyleMain test bootJar sonarqube

  - name: sync-reports
    image: alpine:3.16.0
    commands:
      - mkdir -p /var/webfiles/${DRONE_BUILD_NUMBER}
      - cp -r build/reports /var/webfiles/${DRONE_BUILD_NUMBER}
    volumes:
      - name: webfiles
        path: /var/webfiles
    when:
      status: [ success, failure ]

  - name: publish-docker-develop
    image: plugins/docker:19.03.8
    settings:
      registry: quay.io
      repo: quay.io/fivium/supply-chain-action-plan
      tags:
        - develop
      config:
        from_secret: docker_config
    when:
      branch:
        - develop
      status:
        - success

  - name: publish-docker
    image: plugins/docker:19.03.8
    settings:
      registry: quay.io
      repo: quay.io/fivium/supply-chain-action-plan
      tags:
        - ${DRONE_BRANCH/\//-}-${DRONE_BUILD_NUMBER}
      config:
        from_secret: docker_config
    when:
      branch:
        - main
        - hotfix/**
        - release/**
      status:
        - success

  - name: trivy-build-image
    image: docker:20.10.9
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
    commands:
      - docker build -t quay.io/fivium/scap:trivy-scan-target .

  - name: trivy-scan
    image: aquasec/trivy:0.20.0
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
      - name: drone-trivy-cache
        path: /root/trivy-cache
      - name: webfiles
        path: /var/webfiles
    commands:
      # timeout set as initial cache population can seemingly take a while sometimes
      - trivy --format template --template "@contrib/html.tpl" -o /var/webfiles/${DRONE_BUILD_NUMBER}/trivy-scan.html image --timeout 30m --exit-code 1 quay.io/fivium/scap:trivy-scan-target
    when:
      status:
        - success

  - name: deploy-dev-st
    image: plugins/downstream:linux-amd64
    settings:
      server: https://drone.fivium.co.uk
      token:
        from_secret: drone_token
      fork: true
      repositories:
        - fiviumuk/fivium-dev-app@master
    when:
      branch:
        - develop
      status:
        - success

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: drone-cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./node_modules
        - ./gradle_cache
        - ./sonar_cache

  - name: slack
    image: plugins/slack
    settings:
      webhook: https://hooks.slack.com/services/UPDATE_WEBHOOK
      channel: oga-scap-builds
      template: "*{{build.status}}* <{{build.link}}|Commit {{truncate build.commit 7}} on {{build.branch}} by ${DRONE_COMMIT_AUTHOR_NAME}>\nReports published to: http://drone-assets.fivium.local:9090/scap/{{build.number}}/"
    when:
      status: [ success, failure ]

trigger:
  event:
    include:
    - push

volumes:
  - name: webfiles
    host:
      path: /home/fivium/www/supply-chain-action-plan

  - name: drone-cache
    host:
      path: /home/fivium/drone-cache

  - name: docker-sock
    host:
      path: /var/run/docker.sock

  - name: drone-trivy-cache
    host:
      path: /root/.cache/

---

kind: secret
name: docker_config
data: 3AfT+MPy2inIIbFK635uz30e9DTHH5ePU0WGKVWvFxixURAGNOQqRL64HqGlqG+n53HlLz9MzHLu8XoArsx5efGffjdr3LbTCP1T05rFfUJl8SNYoA1HyHnJUvKR1caM0kEyg7Ydeqv6ZjluPTCACjoPSQjsJJACQ3AeD6BdvuagINqAOfrGXN/jIh5sB1LZYOQgUVkcEPXIe3Hz04S/6ZRlJzAS94NuKoNNT3oOJg3e+0EXy/+mTpqSDlMsrN3kOEvDo9sQqFdIgx5JDrtUKhh+zKLYY2k/OYjBfSVr7LXHIVLIPo9a/mYCMF7R3Dh/FojUrHFPxkU0eKaeAkjoqOzAUIHLRHXqnKIlGXFeqg==
---

kind: secret
name: sonarcloud_token
data: Xl4S16Tgul+zX9m1HMzBm/gX8jcPxIePV1YBz78RKL5vlZYjAr1XPBpRNx9J94duGnhwVzlGx/nTWIzxeJU/HXcG4B4=

---

kind: secret
name: bitbucket_ssh_key
data: rRW1ISha5oByh71TQH2GqJoDNoehGqfZHnzj1S9SnGBndFbTkvwAZH3FoN4M69wPolup6KF3+bp+3HE5xGID4T2hoQXaxCd7G/Cikb2qBCRr77MLm1QEzINDwlWD80NB7vR8P9kzgAmxMyVHG6PVvboEo6oFPAKiwnMnt46CAb824Ul9mWMuQzl5v2Em6mXx93EliYg+Yr84c7q/TJ4CTkOIRtgWgq6o7U61Mecp8fuwEn3I4lqrZicsov4+WweZYxFDUYXCRyt3DbUB/6mP++zSYL2meUvctNzSZ3gYVCV9oeZ6SQ6J8ZsjbC0hstaOM3Ke5F7aF6m/50e60SxoVVSwRbrpiiPmos0fBc5BIYXMSVnVPca4nnE4/Jxz7V2zsB29EbTuBjrelbTVE5fT3OSGcjcRjWUu2O0YYIuFiAfv3zTUcatjM1aIYj4zmATDw2aEsz7NUB2q9DvwD0Qu5XnAMdYGfzVGN7qTQkLfwGA3y0Y2FZNhg1Gq8u6gYQ+h7KyFOjpAvjVEjxlXz8vEpd893RX/Uw/su1BHhgSw2I9Lv3nRyscMgnPTVZgJm9CysnkYFVJ4SVfnTnzbiIc+/YMmJ+LZIEPlm2kpThIyCEJK+nOJkACIEHAGrKzZz3U8WBHcTKx/HK5hNU4nrN/GjfgZMybn5rk+NtFDIGYfVmf9zMoyONGSh1JcIioddyMpjbu9PTT8JOChDfa5tdoJmr+zKUaZdl9LD1IdeSghoe/0DkBqwSzb6TrMzqsikRv/TriFPPpOA2qarPTKzxd2vhaAgETYiDDID285a05j3OYrH2icTHVVql/r0VQnVJdswNdHR4+3s8Qcd07kV6UgaN0nXQC9bBINtk1rRZj6VARrUDi20Zst4D1QEtZmeYQkdNmlh7xW2Xe2u49XmjFMg50vZWHkmXdviLlj8GG9+8a1nqrSatkeMJ9hKG+O6aoJhwwQS6img8fPUJbKVgYiQjWhqW6lR5tckyHq1j0STxND8wVf2eg4VjI0UcpkRIQ2fVkNAZDb1PM5SrlPpJF8XU5romH+xcPeQBA8cW9dIhJmPDLHWN/eBZlc5jEJvOClRJnPXVfIY7ehD6xVrBJjTrra+413whFXg36ROzYchHPwehyal7X+lrJXd18+7zOQiwNAjNPF13juOlz0+MeOQeRP1zIjdULpv7Tb/KuVNzYMM+6QgNubJFmIFMtA8VBHiARc5sltxYlyDa9H92PS+9TUi06XUmvbdYsSWWm1dM55Ara+nGG+HTGP9ZEmMGATPVocuUNmTy587aGiuecBos0lWfzTHDVeOgC4h2vrurp/7Jfkl5nir7YRPTG1NB3BKTA3RBCrVJpkGyeMO13i0GumNWmv9eVMn1e4DBn+U6+asZgso+j+M4NkO9a6OY2SxxaMxJJT3PveCDQZOf7P26Z+TZ/hoSuRR/Xnr2KgziM3kjQkbsSEDzy5dtqBFHU7wyghmkYQa+vh5MPWIuIggUctDKVx5dt5B9jileMTICDD1/6CQQKrnfplIDIh+IMlT+B5g6Ft70L2QFF4Xx687n4MIvGfFmUD2MNEHSl9CEgVeblostRDFFtSSDz/yH/2UkT1o4Ckv+7p8w//1av6nD8KwwkCZ5JVJDfR10pHOAOeyoN+r0cGHdnuE1JwlGkw9vq0/UjBvJ3HbO9+3QNFXWFsDbQ59YWlGZyckgYmd4BeHJMVxlks5FiDV8MYCeuz9NN59xDm6mpCNsQzwm2lbedN9rdia5Q1uNpjxjJhCAGwyYWjscdXrRfMLFasXPx0BtTTh0jhXS8BPSe0ClK+tqP8ZaYOWEGj+ENVL6XJcRTN9s4DWVhJJdzQv8/rdNq0LTEY8MOvAnmznLrgDWnCzMMfOd3ic3tvlMylL9pQMw1EuquMA1rl28tLCsUbCEduCem+3cMxIInYpmDuN+U+KyChmTGUSdkM0tpU/Zur+8ifdCXD/GGVo70wXUym0UybGXHA+X46LTM3toI1Ha0EoRxez2oEKY1TJ3RMnfrMRJd8kCwhXr8F4oqme9OI5QcRWIxaQvQ5biYid43O5DRQ29NwxMqUClK29/39gujIupr56el2ufVxSDwf7Q1rc3cPG3Pa4eNqam5XzpfmsZwITRZxIpl6cEnSXNqNJDpnclR9Cm06aZhyB2sTUZI+/Crg5g5RLOO4nNqzfrMrLoHmVEM0SO+XGo3Rlch9p53OvCuCrqe6FF+C5oak/0PH1TTnNLmJM8BSq2xVCsVp8wFYlLqjlbr5kDrOQtqwXjO2kllICT0tRWW3UrvX312HzVt/zEFWpLCmXDYX84bEbEXOe86+BpJakBiHt0+BPk8hwrQnHIyZq0OzBnx2JzohMikBvCChyMDUlNPgOwexKT2egcIDjt9fsM3Tvf8FO+l1VUUDfiqgCtFYYQ7RX/AjrH977poiKuygvjwiayDdpu/QBXPGUfx/SEA6Edvj/nVJrV5kM5qLNdfvftBNZ6Nfb4dKgjzteEu99wlQsti/t2sufTpEb5xqJ2ZymHG4dPaWlU01xTk9JMtnr+51Ktdeb60kh0NtTGN6LAWai21r69jtbtR0rBkSRULoWPt3w9PizgmVTosSEm88D3DCSP1MT0gQKyQzW1MRKLNEnyCdMSz0vI4uIHbf6H1htPco1FxN0UzZw4aCKy5oCvzPjYlHWGKhB4qUoLOuIAfCL8o0ztSI2ww+N6c/Pz/ZLxH5t6fFE5U2ibQJXzPENOU42lRvzs1aPjMsg4bn9rGH5ZyyqF7lBMK4jEF0fy3UomBanC/Xdcboa5B+8yafNf7mgxrPr8AJ/jqo3YWHsLmROYpeLGq82XSU7OW6kUKTmhznpZM1QuJnU6dq6pESYGzyR6+xiw2ihho+yfDNyUGla1mc77alcIvzpRWacsp0wvU23xtU1bs4oDBXWq8eovDlIf/S1X7Dp0g6eGpqh1X/152uC8RxkMoyiWIMlpUANHioVnet7M5hDa2l65gHxJ1IL9YTDjsN0XIztnxqhNlmndeznagtRYAVLOnOjin2DPhbJkIGKTvFbPygS8Aa5ERbxpQjTeoaRUeRnF7K2Joj1/UQ7wzItrmVPeJbnPxDKg0R+80Jk6q1NqccipjD86FEzD2T1JiNyVB8zxaKjlXj+59LH4KR1QaC/NN4vRAxBlTifE4RyQ8QAks1w7moJ4uLf8wFGaLrTVWqKUAn3nuukVFAspjk6FwnTDmoydHM3ffmxVljQsNgfCeHum1aH90+KKWGo0R+JW9tPB4jOzD2M/+BH2o+0qRICR/suNYtlx8gKViIYPTXnBo4XBmxauGSh8c9Ui6IpSlbvJbuv0iNCB5m3M8AUSotAUtryUgjiFbb8EpIdWC9eCly6wbv3KOCEZZ3TNixg6JWle0Jd3aa87iVQgB8Uzhk076wB7R4k9Czywf0Crk3BuAgIYUP//9ApOEfrOT/8GKnuKWg48xkE9a0IF1ogE289rnE+7IV3E+Dn0yQ1xMNj8SBcg==
---

kind: secret
name: drone_token
data: bPLBgvjQfCVw1+KIB5dG+oGivGuuD2Ts5B4OjtE+XdHjdy0QdX2V/zezmyIG/QXjcXe1CqoOAFX5syHO