saml.entity-id=energy-portal-accounts-service-local
saml.login-url=http://localhost:8081/accounts/saml/login
energy-portal.logout-url=http://localhost:8081/accounts/service-provider-sign-out
saml.consumer-service-location=http://localhost:8080${server.servlet.context-path}/login/saml2/sso/saml