package uk.co.nstauthority.scap.permissionmanagement;


import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyLong;
import static org.mockito.ArgumentMatchers.refEq;
import static org.mockito.Mockito.doAnswer;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.verifyNoInteractions;
import static org.mockito.Mockito.when;

import java.time.Instant;
import java.util.Optional;
import java.util.Set;
import java.util.UUID;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import uk.co.fivium.energyportal.serviceproviders.epmq.messages.ServiceProviderTeamRolesEpasMessage;
import uk.co.fivium.energyportal.serviceproviders.epmq.messages.ServiceProviderUserTeamRolesDto;
import uk.co.fivium.energyportal.starter.configuration.EnergyPortalAccountsConfigurationProperties;
import uk.co.nstauthority.scap.audit.AuditRevisionUtil;
import uk.co.nstauthority.scap.authentication.ServiceUserDetail;
import uk.co.nstauthority.scap.energyportal.EnergyPortalUserService;
import uk.co.nstauthority.scap.energyportal.WebUserAccountId;
import uk.co.nstauthority.scap.permissionmanagement.teams.TeamMemberRoleService;
import uk.co.nstauthority.scap.permissionmanagement.teams.TeamService;

@ExtendWith(MockitoExtension.class)
class TeamRolesUpdateHandlerTest {

  private static final String SERVICE_NAME = "service-name";
  private static final UUID TEAM_ID = UUID.randomUUID();
  private static final Long USER_WUA_ID = 1L;
  private static final Long INVOKING_USER_WUA_ID = 2L;
  private static final ServiceProviderUserTeamRolesDto SERVICE_PROVIDER_USER_TEAM_ROLES_DTO = new ServiceProviderUserTeamRolesDto(
      USER_WUA_ID,
      TEAM_ID.toString(),
      "teamType",
      Set.of("ACCESS_MANAGER")
  );

  @Mock
  private EnergyPortalUserService energyPortalUserService;

  @Mock
  private TeamService teamService;

  @Mock
  private TeamMemberRoleService teamMemberRoleService;

  private final EnergyPortalAccountsConfigurationProperties configurationProperties
      = new EnergyPortalAccountsConfigurationProperties(
          SERVICE_NAME,
      "dev1",
      false,
      false,
      null,
      null
      );

  private TeamRolesUpdateHandler teamRolesUpdateHandler;

  private ServiceProviderTeamRolesEpasMessage message;

  @BeforeEach
  void setUp() {
    teamRolesUpdateHandler = new TeamRolesUpdateHandler(
        energyPortalUserService,
        teamService,
        teamMemberRoleService,
        configurationProperties
    );

    message = new ServiceProviderTeamRolesEpasMessage(
        SERVICE_NAME,
        "correlationId",
        Instant.now(),
        SERVICE_PROVIDER_USER_TEAM_ROLES_DTO,
        INVOKING_USER_WUA_ID
    );
  }

  @Test
  void accept_whenMessageNotForService_thenDoNothing() {
    message.setService("different-service");

    teamRolesUpdateHandler.accept(message);

    verifyNoInteractions(teamMemberRoleService);
  }

  @Test
  void accept_whenInvalidTeam_thenDoNothing() {
    when(teamService.findTeam(TeamId.valueOf(TEAM_ID))).thenReturn(Optional.empty());

    teamRolesUpdateHandler.accept(message);

    verifyNoInteractions(teamMemberRoleService);
  }

  @Test
  void accept_whenValidMessage_thenUpdateTeamRoles() {
    var team = TeamTestUtil.Builder().build();
    when(teamService.findTeam(TeamId.valueOf(TEAM_ID))).thenReturn(Optional.of(team));

    var invokingUserEnergyEnergyPortalUserDto = EnergyPortalDtoTestUtil.Builder().build();
    when(energyPortalUserService.findByWuaId(
        refEq(WebUserAccountId.valueOf(INVOKING_USER_WUA_ID.toString()))
    )).thenReturn(Optional.of(invokingUserEnergyEnergyPortalUserDto));

    // Verify that the call to teamManagementService are wrapped in withFallbackAuditUser,
    // so that the audit revisions generated by setting the roles have the correct associating wuaIds.
    doAnswer(invocation -> {
      assertThat(AuditRevisionUtil.getFallbackAuditUser())
          .usingRecursiveComparison()
          .isEqualTo(ServiceUserDetail.from(invokingUserEnergyEnergyPortalUserDto));
      return null;
    }).when(teamMemberRoleService).updateUserTeamRoles(any(), anyLong(), any());

    teamRolesUpdateHandler.accept(message);

    verify(teamMemberRoleService).updateUserTeamRoles(
        team,
        USER_WUA_ID,
        Set.of("ACCESS_MANAGER")
    );
  }
}